In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv("C:\\Users\\prati\\Documents\\Dsbda\\Data analutics 3\\iris.csv")
df.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [36]:
df.describe

<bound method NDFrame.describe of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [37]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [38]:
X=df.drop('species',axis=1)
y=df['species']

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [40]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train=std.fit_transform(X_train)
X_test=std.transform(X_test)

In [41]:
X_test

array([[ 0.51311821, -1.78796365,  0.34790406,  0.10671977],
       [ 0.63244803, -0.85713659,  0.85428732,  0.88286353],
       [-0.56085014,  1.46993107, -1.28377535, -1.31621046],
       [ 0.27445858, -0.15901629,  0.46043367,  0.23607706],
       [-1.0381694 ,  0.53910401, -1.34004016, -1.31621046],
       [-1.0381694 , -2.48608395, -0.15847921, -0.28135211],
       [ 0.51311821, -1.32255012,  0.62922809,  0.36543435],
       [-0.08353087, -0.85713659,  0.17910964, -0.28135211],
       [-0.91883959,  0.77181078, -1.28377535, -1.31621046],
       [-0.20286069, -0.62442982,  0.40416886,  0.10671977],
       [-0.3221905 , -0.15901629,  0.40416886,  0.36543435],
       [-0.08353087, -0.85713659,  0.74175771,  0.88286353],
       [-0.44152032, -1.78796365,  0.12284483,  0.10671977],
       [-1.15749922, -0.15901629, -1.34004016, -1.31621046],
       [-0.91883959,  1.70263784, -1.28377535, -1.18685317],
       [ 1.10976729, -0.15901629,  0.96681694,  1.14157812],
       [ 0.15512876,  0.

In [42]:
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [43]:
y_predict=model.predict(X_test)
y_predict

array(['versicolor', 'virginica', 'setosa', 'versicolor', 'setosa',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'versicolor', 'setosa', 'setosa', 'setosa',
       'virginica', 'virginica', 'virginica', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica'],
      dtype='<U10')

In [44]:
cm=confusion_matrix(y_test,y_predict)
print("\nConfusion matrix:", cm)


Confusion matrix: [[10  0  0]
 [ 0 13  0]
 [ 0  0  7]]


In [45]:
accuracy=accuracy_score(y_test,y_predict)
print("accuracy :", accuracy)

accuracy : 1.0


In [46]:
precision=precision_score(y_test,y_predict,average='micro')
print("precision: ", precision)

precision:  1.0


In [47]:
recall=recall_score(y_test,y_predict,average='micro')
print("recall: ", recall)

recall:  1.0


In [48]:
f1=f1_score(y_test,y_predict,average='micro')
print("f1: ", f1)

f1:  1.0


In [49]:
error_rate=1-accuracy
print("error_rate", error_rate)

error_rate 0.0


In [50]:
accuracy=accuracy_score(y_test,y_predict)
accuracy

1.0

In [52]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_predict)
print("claasification report: ", report)

claasification report:                precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         7

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

